export const LIVE2D_REQUIRED_PARTS = [
  'body_base',
  'neck',
  'head_base',
  'face_skin',
  'outfit_torso',
  'arm_l',
  'arm_r',
  'eye_white_l',
  'eye_white_r',
  'iris_l',
  'iris_r',
  'eyelid_l',
  'eyelid_r',
  'eyebrow_l',
  'eyebrow_r',
  'mouth_closed',
  'mouth_inner',
  'hair_front',
  'hair_back',
  'hair_side_l',
  'hair_side_r',
] as const;

export type Live2DRequiredPart = (typeof LIVE2D_REQUIRED_PARTS)[number];

export const LIVE2D_PART_LABELS: Record<Live2DRequiredPart, string> = {
  body_base: 'Body base',
  neck: 'Neck',
  head_base: 'Head base',
  face_skin: 'Face skin',
  outfit_torso: 'Outfit torso',
  arm_l: 'Left arm',
  arm_r: 'Right arm',
  eye_white_l: 'Left eye white',
  eye_white_r: 'Right eye white',
  iris_l: 'Left iris',
  iris_r: 'Right iris',
  eyelid_l: 'Left eyelid',
  eyelid_r: 'Right eyelid',
  eyebrow_l: 'Left eyebrow',
  eyebrow_r: 'Right eyebrow',
  mouth_closed: 'Closed mouth',
  mouth_inner: 'Mouth interior',
  hair_front: 'Front hair / bangs',
  hair_back: 'Back hair',
  hair_side_l: 'Left side hair',
  hair_side_r: 'Right side hair',
};

export const LIVE2D_HIDDEN_AREA_PRESETS: Array<{ part: Live2DRequiredPart; note: string }> = [
  { part: 'hair_front', note: 'Face pixels under bangs should exist for head movement.' },
  { part: 'arm_l', note: 'Torso should continue under the separated left arm.' },
  { part: 'arm_r', note: 'Torso should continue under the separated right arm.' },
  { part: 'head_base', note: 'Neck area hidden under the head should be available.' },
  { part: 'mouth_inner', note: 'Open mouth interior should be separate from face skin.' },
];
